export const ALL_COUNTRIES = [
  "Afghanistan", "Albania", "Algeria", "Andorra", "Angola", "Argentina", "Armenia",
  "Australia", "Austria", "Azerbaijan", "Bahamas", "Bahrain", "Bangladesh", "Barbados",
  "Belarus", "Belgium", "Belize", "Benin", "Bhutan", "Bolivia", "Bosnia and Herzegovina",
  "Botswana", "Brazil", "Brunei", "Bulgaria", "Burkina Faso", "Burundi", "Cambodia",
  "Cameroon", "Canada", "Cape Verde", "Central African Republic", "Chad", "Chile",
  "China", "Colombia", "Comoros", "Congo", "Costa Rica", "Croatia", "Cuba", "Cyprus",
  "Czech Republic", "Denmark", "Djibouti", "Dominica", "Dominican Republic", "Ecuador",
  "Egypt", "El Salvador", "Equatorial Guinea", "Eritrea", "Estonia", "Eswatini",
  "Ethiopia", "Fiji", "Finland", "France", "Gabon", "Gambia", "Georgia", "Germany",
  "Ghana", "Greece", "Grenada", "Guatemala", "Guinea", "Guinea-Bissau", "Guyana",
  "Haiti", "Honduras", "Hungary", "Iceland", "India", "Indonesia", "Iran", "Iraq",
  "Ireland", "Israel", "Italy", "Ivory Coast", "Jamaica", "Japan", "Jordan",
  "Kazakhstan", "Kenya", "Kiribati", "Kosovo", "Kuwait", "Kyrgyzstan", "Laos",
  "Latvia", "Lebanon", "Lesotho", "Liberia", "Libya", "Liechtenstein", "Lithuania",
  "Luxembourg", "Madagascar", "Malawi", "Malaysia", "Maldives", "Mali", "Malta",
  "Marshall Islands", "Mauritania", "Mauritius", "Mexico", "Micronesia", "Moldova",
  "Monaco", "Mongolia", "Montenegro", "Morocco", "Mozambique", "Myanmar", "Namibia",
  "Nauru", "Nepal", "Netherlands", "New Zealand", "Nicaragua", "Niger", "Nigeria",
  "North Korea", "North Macedonia", "Norway", "Oman", "Pakistan", "Palau", "Palestine",
  "Panama", "Papua New Guinea", "Paraguay", "Peru", "Philippines", "Poland",
  "Portugal", "Qatar", "Romania", "Russia", "Rwanda", "Saint Kitts and Nevis",
  "Saint Lucia", "Saint Vincent and the Grenadines", "Samoa", "San Marino",
  "Sao Tome and Principe", "Saudi Arabia", "Senegal", "Serbia", "Seychelles",
  "Sierra Leone", "Singapore", "Slovakia", "Slovenia", "Solomon Islands", "Somalia",
  "South Africa", "South Korea", "South Sudan", "Spain", "Sri Lanka", "Sudan",
  "Suriname", "Sweden", "Switzerland", "Syria", "Taiwan", "Tajikistan", "Tanzania",
  "Thailand", "Timor-Leste", "Togo", "Tonga", "Trinidad and Tobago", "Tunisia",
  "Turkey", "Turkmenistan", "Tuvalu", "Uganda", "Ukraine", "United Arab Emirates",
  "United Kingdom", "United States", "Uruguay", "Uzbekistan", "Vanuatu",
  "Vatican City", "Venezuela", "Vietnam", "Yemen", "Zambia", "Zimbabwe",
] as const;

export const MAJOR_CITIES: Record<string, string[]> = {
  "United Kingdom": ["London", "Manchester", "Birmingham", "Edinburgh", "Glasgow", "Liverpool", "Leeds", "Bristol"],
  "France": ["Paris", "Marseille", "Lyon", "Nice", "Toulouse", "Bordeaux", "Strasbourg", "Cannes"],
  "Germany": ["Berlin", "Munich", "Hamburg", "Frankfurt", "Cologne", "Stuttgart", "Dusseldorf"],
  "Italy": ["Rome", "Milan", "Venice", "Florence", "Naples", "Turin", "Bologna"],
  "Spain": ["Madrid", "Barcelona", "Valencia", "Seville", "Malaga", "Bilbao"],
  "Portugal": ["Lisbon", "Porto", "Faro", "Coimbra"],
  "Switzerland": ["Zurich", "Geneva", "Basel", "Bern", "Lausanne", "Lucerne"],
  "Austria": ["Vienna", "Salzburg", "Innsbruck", "Graz"],
  "Netherlands": ["Amsterdam", "Rotterdam", "The Hague", "Utrecht"],
  "Belgium": ["Brussels", "Antwerp", "Bruges", "Ghent"],
  "Ireland": ["Dublin", "Cork", "Galway"],
  "Denmark": ["Copenhagen", "Aarhus", "Odense"],
  "Sweden": ["Stockholm", "Gothenburg", "Malmo"],
  "Norway": ["Oslo", "Bergen", "Trondheim"],
  "Finland": ["Helsinki", "Tampere", "Turku"],
  "Iceland": ["Reykjavik"],
  "Poland": ["Warsaw", "Krakow", "Gdansk", "Wroclaw"],
  "Czech Republic": ["Prague", "Brno"],
  "Greece": ["Athens", "Thessaloniki", "Santorini", "Mykonos"],
  "Croatia": ["Zagreb", "Split", "Dubrovnik"],
  "Hungary": ["Budapest"],
  "Monaco": ["Monaco"],
  "United States": ["New York", "Los Angeles", "Chicago", "Miami", "San Francisco", "Las Vegas"],
  "Canada": ["Toronto", "Vancouver", "Montreal"],
  "India": ["Mumbai", "Delhi", "Bangalore", "Chennai", "Kolkata", "Hyderabad", "Pune"],
  "United Arab Emirates": ["Dubai", "Abu Dhabi", "Sharjah"],
  "Australia": ["Sydney", "Melbourne", "Brisbane", "Perth"],
  "China": ["Beijing", "Shanghai", "Shenzhen", "Guangzhou"],
  "Japan": ["Tokyo", "Osaka", "Kyoto"],
  "Turkey": ["Istanbul", "Ankara", "Antalya"],
  "Russia": ["Moscow", "Saint Petersburg"],
  "Brazil": ["Sao Paulo", "Rio de Janeiro", "Brasilia"],
  "South Africa": ["Cape Town", "Johannesburg", "Durban"],
  "Singapore": ["Singapore"],
  "Malaysia": ["Kuala Lumpur", "Penang"],
  "Thailand": ["Bangkok", "Phuket", "Chiang Mai"],
};
