module.exports = {
  apps: [
    {
      name: "europe-server",
      cwd: "./server",
      script: "npm",
      args: "start",
      env: {
        NODE_ENV: "production",
        PORT: 4005,
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      error_file: "/root/.pm2/logs/europe-server-error.log",
      out_file: "/root/.pm2/logs/europe-server-out.log",
      log_date_format: "DD/MM/YYYY HH:mm:ss",
    },
    {
      name: "europe-client",
      cwd: "./client",
      script: "node_modules/next/dist/bin/next",
      args: "start -p 3002",
      env: {
        NODE_ENV: "production",
        PORT: 3005,
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "800M",
      error_file: "/root/.pm2/logs/europe-client-error.log",
      out_file: "/root/.pm2/logs/europe-client-out.log",
      log_date_format: "DD/MM/YYYY HH:mm:ss",
    },
    {
      name: "europe-admin",
      cwd: "./admin",
      script: "npm",
      args: "run preview -- --port 4174 --host 0.0.0.0",
      env: {
        NODE_ENV: "production",
        PORT: 4174,
      },
      instances: 1,
      exec_mode: "fork",
      autorestart: true,
      watch: false,
      max_memory_restart: "500M",
      error_file: "/root/.pm2/logs/europe-admin-error.log",
      out_file: "/root/.pm2/logs/europe-admin-out.log",
      log_date_format: "DD/MM/YYYY HH:mm:ss",
    },
  ],
};
